import crypto from "node:crypto";
export function cookies(req){const o={};for(const p of String(req.headers.cookie||"").split(";")){const i=p.indexOf("=");if(i>0)o[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())}return o}
function sec(){const s=process.env.OFFICE_SESSION_SECRET||"";return s.length>=32?s:null}
export function signSession(u){const s=sec();if(!s)return null;const p={sub:u.username,role:u.role,exp:Date.now()+43200000},b=Buffer.from(JSON.stringify(p)).toString("base64url"),g=crypto.createHmac("sha256",s).update(b).digest("base64url");return `${b}.${g}`}
export function session(req){const s=sec(),t=cookies(req).jkstory_office_session;if(!s||!t)return null;const [b,g]=String(t).split(".");if(!b||!g)return null;const e=crypto.createHmac("sha256",s).update(b).digest("base64url"),a=Buffer.from(g),z=Buffer.from(e);if(a.length!==z.length||!crypto.timingSafeEqual(a,z))return null;try{const p=JSON.parse(Buffer.from(b,"base64url"));return p.exp>Date.now()?p:null}catch{return null}}
export function role(req,allowed=["admin","operator","viewer"]){const s=session(req);return s&&allowed.includes(s.role)?s:null}
function verify(password,encoded){const [k,i,s,h]=String(encoded||"").split("$");if(k!=="pbkdf2"||Number(i)<210000)return false;const d=crypto.pbkdf2Sync(String(password),s,Number(i),32,"sha256"),e=Buffer.from(h||"","hex");return d.length===e.length&&crypto.timingSafeEqual(d,e)}
export function authenticate(user,password){let us=[];try{us=JSON.parse(process.env.OFFICE_USERS_JSON||"[]")}catch{}const u=us.find?.(x=>x.username===user);if(!u)return null;const ok=u.passwordHash?verify(password,u.passwordHash):(process.env.NODE_ENV!=="production"&&u.password===password);return ok?{username:u.username,role:u.role}:null}
export function sameOrigin(req){const o=req.headers.origin;if(!o)return true;const proto=req.headers["x-forwarded-proto"]||"http",host=req.headers["x-forwarded-host"]||req.headers.host;if(!host)return false;try{return new URL(o).origin===new URL(`${proto}://${host}`).origin}catch{return false}}
export function headers(res){res.setHeader("X-Content-Type-Options","nosniff");res.setHeader("Referrer-Policy","no-referrer");res.setHeader("X-Frame-Options","DENY");res.setHeader("Permissions-Policy","camera=(), microphone=(), geolocation=()")}
export function json(res,status,data){headers(res);res.statusCode=status;res.setHeader("Content-Type","application/json; charset=utf-8");res.setHeader("Cache-Control","no-store");res.end(JSON.stringify(data))}
export async function readJson(req,max=65536){let a=[],n=0;for await(const c of req){n+=c.length;if(n>max)throw new Error("PAYLOAD_TOO_LARGE");a.push(c)}const t=Buffer.concat(a).toString("utf8");return t?JSON.parse(t):{}}
