import fs from "node:fs/promises";import path from "node:path";
const F=process.env.OFFICE_DATA_FILE||path.join(process.cwd(),"data","office-data.json"),RU=process.env.UPSTASH_REDIS_REST_URL||process.env.KV_REST_API_URL||"",RT=process.env.UPSTASH_REDIS_REST_TOKEN||process.env.KV_REST_API_TOKEN||"";
const D={seq:3,tasks:[{id:"TASK-001",title:"기존 프로젝트 구조 조사",team:"개발기획팀",status:"대기",priority:"최우선",createdAt:1},{id:"TASK-002",title:"GitHub 이전 상태 확인",team:"운영관리팀",status:"대기",priority:"높음",createdAt:2},{id:"TASK-003",title:"Vercel 이전 상태 확인",team:"운영관리팀",status:"대기",priority:"높음",createdAt:3}],messages:[{id:"MSG-001",role:"assistant",content:"현재 프로젝트와 Cloud Browser 컨텍스트를 기준으로 지시를 받을 준비가 되어 있습니다.",createdAt:1}],audit:[]};
const redisOn=()=>Boolean(RU&&RT);async function redis(cmd){const r=await fetch(RU,{method:"POST",headers:{Authorization:`Bearer ${RT}`,"Content-Type":"application/json"},body:JSON.stringify(cmd)});if(!r.ok)throw new Error(`REDIS_HTTP_${r.status}`);const d=await r.json();if(d.error)throw new Error(d.error);return d.result}
async function rf(){try{await fs.access(F)}catch{await fs.mkdir(path.dirname(F),{recursive:true});await fs.writeFile(F,JSON.stringify(D,null,2))}return JSON.parse(await fs.readFile(F,"utf8"))}async function wf(d){await fs.mkdir(path.dirname(F),{recursive:true});await fs.writeFile(F+".tmp",JSON.stringify(d,null,2));await fs.rename(F+".tmp",F)}
export const mode=()=>redisOn()?"redis":process.env.NODE_ENV==="production"?"unconfigured":"file";
function hash(a){const o={};for(let i=0;i<(a||[]).length;i+=2)o[a[i]]=a[i+1];return o}
export async function tasks(){if(redisOn()){let ids=await redis(["ZRANGE","jk:tasks","0","-1","REV"])||[];if(!ids.length){for(const t of D.tasks){await redis(["HSET",`jk:task:${t.id}`,"id",t.id,"title",t.title,"team",t.team,"status",t.status,"priority",t.priority,"createdAt",String(t.createdAt)]);await redis(["ZADD","jk:tasks",String(t.createdAt),t.id])}await redis(["SET","jk:task:seq","3"]);ids=await redis(["ZRANGE","jk:tasks","0","-1","REV"])}const out=[];for(const id of ids){const h=hash(await redis(["HGETALL",`jk:task:${id}`]));if(h.id)out.push({...h,createdAt:Number(h.createdAt)})}return out}if(process.env.NODE_ENV==="production")throw new Error("STORE_NOT_CONFIGURED");return (await rf()).tasks}
export async function createTask(x){const title=String(x.title||"").trim().slice(0,500);if(!title)throw new Error("TASK_TITLE_REQUIRED");let id;if(redisOn()){id=`TASK-${String(await redis(["INCR","jk:task:seq"])).padStart(3,"0")}`}else{if(process.env.NODE_ENV==="production")throw new Error("STORE_NOT_CONFIGURED");const d=await rf();d.seq++;id=`TASK-${String(d.seq).padStart(3,"0")}`;await wf(d)}const t={id,title,team:String(x.team||"AI 전산센터").slice(0,100),status:String(x.status||"접수").slice(0,50),priority:String(x.priority||"높음").slice(0,50),createdAt:Date.now()};await save(t);return t}
async function save(t){if(redisOn()){await redis(["HSET",`jk:task:${t.id}`,"id",t.id,"title",t.title,"team",t.team,"status",t.status,"priority",t.priority,"createdAt",String(t.createdAt)]);await redis(["ZADD","jk:tasks",String(t.createdAt),t.id]);return}const d=await rf(),i=d.tasks.findIndex(x=>x.id===t.id);i>=0?d.tasks[i]=t:d.tasks.unshift(t);await wf(d)}
export async function updateTask(id,p){const list=await tasks(),t=list.find(x=>x.id===id);if(!t)throw new Error("TASK_NOT_FOUND");for(const k of ["title","team","status","priority"])if(p[k]!==undefined)t[k]=String(p[k]).slice(0,k==="title"?500:100);await save(t);return t}
export async function messages(){if(redisOn()){const a=await redis(["LRANGE","jk:messages","-100","-1"])||[];return a.map(x=>JSON.parse(x))}if(process.env.NODE_ENV==="production")throw new Error("STORE_NOT_CONFIGURED");return (await rf()).messages}
export async function addMessage(role,content,meta={}){const m={id:`MSG-${Date.now()}`,role:role==="user"?"user":"assistant",content:String(content||"").slice(0,12000),meta,createdAt:Date.now()};if(redisOn()){await redis(["RPUSH","jk:messages",JSON.stringify(m)]);await redis(["LTRIM","jk:messages","-500","-1"]);return m}if(process.env.NODE_ENV==="production")throw new Error("STORE_NOT_CONFIGURED");const d=await rf();d.messages.push(m);d.messages=d.messages.slice(-500);await wf(d);return m}
export async function audit(event,actor,details={}){const a={id:`AUD-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,event,actor,details,createdAt:Date.now()};if(redisOn()){await redis(["RPUSH","jk:audit",JSON.stringify(a)]);await redis(["LTRIM","jk:audit","-1000","-1"]);return a}if(process.env.NODE_ENV==="production")return a;const d=await rf();d.audit.push(a);d.audit=d.audit.slice(-1000);await wf(d);return a}
export async function audits(){if(redisOn()){const a=await redis(["LRANGE","jk:audit","-100","-1"])||[];return a.map(x=>JSON.parse(x)).reverse()}if(process.env.NODE_ENV==="production")throw new Error("STORE_NOT_CONFIGURED");return (await rf()).audit.slice(-100).reverse()}
const B=new Map();export async function rate(key,limit=20,secs=60){if(redisOn()){const k=`jk:rate:${key}`,n=Number(await redis(["INCR",k]));if(n===1)await redis(["EXPIRE",k,String(secs)]);return n<=limit}const now=Date.now(),b=B.get(key);if(!b||b.until<now){B.set(key,{n:1,until:now+secs*1000});return true}b.n++;return b.n<=limit}
export async function backup(){return {version:1,exportedAt:new Date().toISOString(),mode:mode(),tasks:await tasks(),messages:await messages(),audit:await audits()}}
